### ISSUE TITLE
When visitor views a Recipient, s/he Sees Info about the Recipient and All "Future"/Outstanding Needs for that Recipient

### ISSUE THREAD

**Issue by ghost** [kjs222/pivot#15]
-The recipients name and description are shown
-The associated charity is named (with logo)
-All items for that recipient are shown - with option to select number of items to purchase, the price of the item, and a button that will add the item/s to the cart.
-Item details are shown for each item.
-The visitor can click on any of the following buttons:
-See all recipients for [this charity]
-See all recipients for [this cause]
-See all recipients for [this type of need]

**Comment by kjs222** [comment]
Pending routes, these pieces need to be added to family show:

# The visitor can click on any of the following buttons:

# See all recipients for [this charity]

# See all recipients for [this cause]

# See all recipients for [this type of need]
