### ISSUE TITLE
Visitor is prompted to log in or create account on checkout and Visitor can Create Account/Login/Logout

### ISSUE THREAD

**Issue by ghost** [kjs222/pivot#21]

**Comment by kjs222** [comment]
- when a vistor goes to /users/new he/she can create an account
  - if username is already taken, user gets an informative flash message and the new form is re-rendered
  - if any required fields are not entered, user gets an informative flash message and the new form is re-rendered
  - when account is successfully created, user gets an informative flash method and the /dashboard page is displayed
  - The user's username is appears in the nav bar and a logout button appears on the nav bar
  - When the logout button is clicked, the user is taken to the root page; the user name is not present on the nav bar and a login button is shown on the have bar
  - When you click on the login button in the nav bar, you go to /login page.  
  - If the user enters his/her correct creditials, he is logged in, goes to /dashboard, username is in nav bar, and logout button is present
  - if the user enters incorrect password, he/she is given an informative flash message, and login form is re-rendered
